"""add_vacation_table

Revision ID: 3b328caadefa
Revises: 3196b62ef538
Create Date: 2023-10-12 10:44:02.569257

"""
from alembic import op
import sqlalchemy as sa

from app.model.base import CustomUUID

# revision identifiers, used by Alembic.
revision = '3b328caadefa'
down_revision = '3196b62ef538'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vacation',
    sa.Column('id', CustomUUID(as_uuid=True), nullable=False),
    sa.Column('type', sa.Enum('paid', 'unpaid', name='vacationtype'), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vacation_id'), 'vacation', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vacation_id'), table_name='vacation')
    op.drop_table('vacation')
    # ### end Alembic commands ###
